apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: machinmax13/ci-cd:latest  # Assurez-vous que cette image correspond à celle que vous avez poussée
        ports:
        - containerPort: 8080  # Modifiez si votre application utilise un autre port
