apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd
  template:
    metadata:
      labels:
        app: ci-cd
    spec:
      containers:
      - name: ci-cd
        image: machinmax13/ci-cd:latest  # Assurez-vous d'utiliser le bon tag
        ports:
        - containerPort: 8080  # Changez ce port selon ce que votre application utilise

---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-service
spec:
  type: NodePort
  ports:
    - port: 8080  # Port utilisé par votre application
      targetPort: 8080
  selector:
    app: ci-cd

 