apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1  # Nombre de réplicas souhaités
  selector:
    matchLabels:
      app: myapp  # Étiquette à matcher avec le service
  template:
    metadata:
      labels:
        app: myapp  # Étiquetage du pod
    spec:
      containers:
      - name: myapp
        image: machinmax13/ci-cd:latest  # Assurez-vous que l'image est correcte
        ports:
        - containerPort: 8080  # Port que l'application écoute


---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 8080  # Port utilisé par votre application
      targetPort: 8080
  selector:
    app: myapp

 