name: Node.js CI/CD

on:
  push:
    branches: 
      - main
    tags:
      - '*'  # Déclenche le workflow pour n'importe quel tag
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Tester sur différentes versions de Node.js

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      working-directory: ./app

    - name: Run Tests
      run: npm test
      working-directory: ./app
